### ISSUE TITLE
Needs updating for Python3

### ISSUE THREAD

**Issue by diveyez** [stef/wireless-radar#3]
root@base-Rpi3B:~/wireless-radar # ./setup.py
./setup.py: line 2: import: command not found
from: can't read /var/mail/setuptools
./setup.py: line 9: syntax error near unexpected token `('
./setup.py: line 9: `def read(fname):'

**Comment by stef** [comment]
fixed in https://github.com/stef/wireless-radar/commit/e86a99e4306ca98ecde9a75549a957f39c37b9ce and v0.2.3

**Comment by stef** [comment]
thanks for reporting!
