### ISSUE TITLE
UnicodeDecodeError on Install

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [stef/wireless-radar#5]
When I try to pip install this module, I keep getting this error: `UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4085: character maps to <undefined>`

Full install log:

> Collecting wireless-radar
>   Using cached https\://files.pythonhosted.org/packages/56/8/c4694f43d5592629d9e2281c1d1cbbd950a533c320ca9d8819fc4d4d6e59/wireless-radar-0.2.3.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "\<string>", line 1, in <module>
>       File "C:\Users\HPOWNE\~1\AppData\Local\Temp\pip-install-ntev7tyc\wireless-radar\setup.py", line 31, in <module>
>         long_description=read('README.md'),
>       File "C:\Users\HPOWNE\~1\AppData\Local\Temp\pip-install-ntev7tyc\wireless-radar\setup.py", line 10, in read
>         return open(os.path.join(os.path.dirname(_\_file__), fname)).read()
>       File "C:\Users\HP Owner\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4085: character maps to <undefined>
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\HPOWNE\~1\AppData\Local\Temp\pip-install-ntev7tyc\wireless-radar\

This error occurs in Windows 7 (Version 6.1 Build 7601: Service Pack 1), Python 3.7.1, pip 19.0.3

**Comment by stef** [comment]
this is strange, when i install this in a clean virtualenv i get this:
```
└─(03:25)── 1:% pip install wireless-radar                                                                                                                                        ──(Tue,Mar05)─┘
Collecting wireless-radar                                                                                                                                                                        
Collecting pybluez (from wireless-radar)                                                                                                                                                         
  Using cached https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip                                                       
Requirement already satisfied: python-wifi>=0.5.0 in ./env/lib/python3.6/site-packages (from wireless-radar) (0.6.1)                                                                             
Requirement already satisfied: netaddr in ./env/lib/python3.6/site-packages (from wireless-radar) (0.7.19)                                                                                       
Requirement already satisfied: scapy in ./env/lib/python3.6/site-packages (from wireless-radar) (2.4.2)                                                                                          
Building wheels for collected packages: pybluez                                                                                                                                                  
  Building wheel for pybluez (setup.py) ... done                                                                                                                                                 
  Stored in directory: /home/user/.cache/pip/wheels/e1/0c/0e/2d49f6281421e48d31af681559baef6b3ffa82d54f12115ce3                                                                                     
Successfully built pybluez                                                                                                                                                                       
Installing collected packages: pybluez, wireless-radar                                                                                                                                           
Successfully installed pybluez-0.22 wireless-radar-0.2.3                                                                                                                                         
(env) % python --version
Python 3.6.7                                                                                                                                                                                     
```

**Comment by HeyITGuyFixIt** [comment]
I just tried it in a virtualenv and I got the exact same response as before.

**Comment by stef** [comment]
can you try cloning the git repo, and running setup.py directly? if that fails, you could try to truncate the README.md file to an empty file and try that way, i guess it should work that way.

**Comment by stef** [comment]
oh, i just see this in your log:
> File "C:\Users\HP Owner\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py",

that looks like the wrong encoding. dunno how you set the encoding in windows, but it should be i guess utf8 instead of cp1252.

**Comment by HeyITGuyFixIt** [comment]
Seems the offending line is [this line](https://github.com/stef/wireless-radar/blob/master/setup.py#L10), and from what I have [read](https://stackoverflow.com/a/9233174/11124687), the solution is to set the encoding option. Perhaps check if the OS is Windows, and if it is, set the encoding option to `UTF-8`. So something like 
```python
def read(fname):
    if os.name == 'nt':
        return open(os.path.join(os.path.dirname(__file__), fname), encoding='UTF-8').read()
    else:
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
```

**Comment by stef** [comment]
i committed a fix so it works on py2 too, and bumped the version, so it should work now also via pypi. thanks for reporting and the fix!
